In [1]:
from tensorflow import keras

In [2]:
# Load Data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(y_train.shape)

(60000,)


In [4]:
for i in range(5):
    print(y_train[i])

5
0
4
1
9


In [5]:
# one hot encoding 
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [6]:
for i in range(5):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [7]:
print(x_train.shape, x_test.shape)

(60000, 28, 28) (10000, 28, 28)


In [8]:
x_train = x_train.reshape([60000,28*28])
x_test = x_test.reshape([10000,28*28])

In [9]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [10]:
model = keras.Sequential()
model.add(keras.layers.Dense(32, activation="sigmoid", input_shape=(28*28,)))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(10, activation="sigmoid"))

In [11]:
optimizer = keras.optimizers.SGD(lr=0.1)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                25120     
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 10)                330       
Total params: 26,506
Trainable params: 26,506
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x_train, y_train,
          batch_size=32,
          epochs=10,
          validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 12s 198us/step - loss: 1.2910 - acc: 0.6277 - val_loss: 0.9458 - val_acc: 0.7049
Epoch 2/10
60000/60000 [==============================] - 11s 176us/step - loss: 1.0304 - acc: 0.6511 - val_loss: 1.2064 - val_acc: 0.5442
Epoch 3/10
60000/60000 [==============================] - 11s 176us/step - loss: 0.9214 - acc: 0.6791 - val_loss: 0.9003 - val_acc: 0.6859
Epoch 4/10
60000/60000 [==============================] - 11s 175us/step - loss: 0.8315 - acc: 0.7197 - val_loss: 0.7198 - val_acc: 0.7754
Epoch 5/10
60000/60000 [==============================] - 11s 175us/step - loss: 0.8348 - acc: 0.7211 - val_loss: 0.8090 - val_acc: 0.7147
Epoch 6/10
60000/60000 [==============================] - 10s 174us/step - loss: 0.8282 - acc: 0.7141 - val_loss: 0.8249 - val_acc: 0.7132
Epoch 7/10
60000/60000 [==============================] - 11s 175us/step - loss: 0.8125 - acc: 0.7233 - val_loss: 0.

In [13]:
model.evaluate(x_test,y_test)

10000/10000 [==============================] - 1s 67us/step


[0.6589932903766632, 0.7757]

In [14]:
model.fit(x_train, y_train,
          batch_size=256,
          epochs=10,
          validation_data=(x_test, y_test))

model.evaluate(x_test,y_test)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 2s 26us/step - loss: 0.6616 - acc: 0.7779 - val_loss: 0.6344 - val_acc: 0.7890
Epoch 2/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.6458 - acc: 0.7880 - val_loss: 0.6231 - val_acc: 0.7940
Epoch 3/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.6246 - acc: 0.7964 - val_loss: 0.6136 - val_acc: 0.8007
Epoch 4/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.6151 - acc: 0.7995 - val_loss: 0.5986 - val_acc: 0.8045
Epoch 5/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.6157 - acc: 0.8001 - val_loss: 0.5936 - val_acc: 0.8064
Epoch 6/10
60000/60000 [==============================] - 2s 27us/step - loss: 0.6090 - acc: 0.8033 - val_loss: 0.5853 - val_acc: 0.8101
Epoch 7/10
60000/60000 [==============================] - 2s 26us/step - loss: 0.5920 - acc: 0.8065 - val_loss: 0.5750 - val_acc

[0.5630424203395844, 0.8176]