In [1]:
from tensorflow import keras

In [2]:
# Load Data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(y_train.shape)

(60000,)


In [4]:
for i in range(5):
    print(y_train[i])

5
0
4
1
9


In [5]:
# one hot encoding 
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [6]:
for i in range(5):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [7]:
print(x_train.shape, x_test.shape)

(60000, 28, 28) (10000, 28, 28)


In [8]:
x_train = x_train.reshape([60000,28*28])
x_test = x_test.reshape([10000,28*28])

In [9]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [10]:
model = keras.Sequential()
model.add(keras.layers.Dense(128, activation="sigmoid", input_shape=(28*28,)))
model.add(keras.layers.Dense(128, activation="sigmoid"))
model.add(keras.layers.Dense(10, activation="sigmoid"))

In [11]:
optimizer = keras.optimizers.SGD(lr=0.1)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 128)               100480    
_________________________________________________________________
dense_1 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_2 (Dense)              (None, 10)                1290      
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train, y_train,
          batch_size=32,
          epochs=10,
          validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 30s 497us/step - loss: 0.8516 - acc: 0.7650 - val_loss: 0.7264 - val_acc: 0.7687
Epoch 2/10
60000/60000 [==============================] - 17s 289us/step - loss: 0.7074 - acc: 0.7776 - val_loss: 0.7019 - val_acc: 0.7652
Epoch 3/10
60000/60000 [==============================] - 18s 300us/step - loss: 0.6654 - acc: 0.7857 - val_loss: 0.5980 - val_acc: 0.8108
Epoch 4/10
60000/60000 [==============================] - 18s 298us/step - loss: 0.7218 - acc: 0.7640 - val_loss: 0.6950 - val_acc: 0.7810
Epoch 5/10
60000/60000 [==============================] - 18s 294us/step - loss: 0.6939 - acc: 0.7717 - val_loss: 0.6617 - val_acc: 0.7818
Epoch 6/10
60000/60000 [==============================] - 18s 295us/step - loss: 0.6716 - acc: 0.7802 - val_loss: 0.7066 - val_acc: 0.7724
Epoch 7/10
56736/60000 [===========================>..] - ETA: 0s - loss: 0.6428 - acc: 0.7921

In [ ]:
model.evaluate(x_test,y_test)

In [ ]:
model.fit(x_train, y_train,
          batch_size=256,
          epochs=10,
          validation_data=(x_test, y_test))

model.evaluate(x_test,y_test)