In [1]:
from tensorflow import keras

In [2]:
# Load Data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(y_train.shape)

(60000,)


In [4]:
for i in range(5):
    print(y_train[i])

5
0
4
1
9


In [5]:
# one hot encoding 
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [6]:
for i in range(5):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [7]:
print(x_train.shape, x_test.shape)

(60000, 28, 28) (10000, 28, 28)


In [8]:
x_train = x_train.reshape([60000,28*28])
x_test = x_test.reshape([10000,28*28])

In [9]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [10]:
model = keras.Sequential()
model.add(keras.layers.Dense(512, activation="sigmoid", input_shape=(28*28,)))
model.add(keras.layers.Dense(512, activation="sigmoid"))
model.add(keras.layers.Dense(10, activation="sigmoid"))

In [11]:
optimizer = keras.optimizers.SGD(lr=0.1)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=['accuracy'])

model.summary()

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 512)               401920    
_________________________________________________________________
dense_2 (Dense)              (None, 512)               262656    
_________________________________________________________________
dense_3 (Dense)              (None, 10)                5130      
Total params: 669,706
Trainable params: 669,706
Non-trainable params: 0
_________________________________________________________________


In [12]:
model.fit(x_train, y_train,
          batch_size=32,
          epochs=10,
          validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================]60000/60000 [==============================] - 9s 154us/step - loss: 0.6201 - acc: 0.8109 - val_loss: 0.5949 - val_acc: 0.7883

Epoch 2/10
60000/60000 [==============================]60000/60000 [==============================] - 9s 152us/step - loss: 0.5557 - acc: 0.8219 - val_loss: 0.5357 - val_acc: 0.8315

Epoch 3/10
60000/60000 [==============================]60000/60000 [==============================] - 9s 150us/step - loss: 0.5444 - acc: 0.8251 - val_loss: 0.4277 - val_acc: 0.8711

Epoch 4/10
60000/60000 [==============================]60000/60000 [==============================] - 9s 150us/step - loss: 0.5148 - acc: 0.8361 - val_loss: 0.4489 - val_acc: 0.8626

Epoch 5/10
60000/60000 [==============================]60000/60000 [==============================] - 9s 149us/step - loss: 0.4933 - acc: 0.8433 - val_loss: 0.4307 - val_acc: 0.8663

Epoch 6/10
60000/60000 [===========

In [13]:
model.evaluate(x_test,y_test)

10000/10000 [==============================]10000/10000 [==============================] - 0s 47us/step



[0.3953757485985756, 0.8728]

In [14]:
model.fit(x_train, y_train,
          batch_size=256,
          epochs=10,
          validation_data=(x_test, y_test))

model.evaluate(x_test,y_test)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================]60000/60000 [==============================] - 3s 52us/step - loss: 0.3328 - acc: 0.8989 - val_loss: 0.3167 - val_acc: 0.9007

Epoch 2/10
60000/60000 [==============================]60000/60000 [==============================] - 3s 53us/step - loss: 0.3177 - acc: 0.9042 - val_loss: 0.3115 - val_acc: 0.9046

Epoch 3/10
60000/60000 [==============================]60000/60000 [==============================] - 3s 56us/step - loss: 0.3042 - acc: 0.9079 - val_loss: 0.2881 - val_acc: 0.9114

Epoch 4/10
60000/60000 [==============================]60000/60000 [==============================] - 3s 53us/step - loss: 0.2932 - acc: 0.9109 - val_loss: 0.2898 - val_acc: 0.9105

Epoch 5/10
60000/60000 [==============================]60000/60000 [==============================] - 3s 53us/step - loss: 0.2809 - acc: 0.9155 - val_loss: 0.2771 - val_acc: 0.9126

Epoch 6/10
60000/60000 [================

[0.2581963325738907, 0.9183]