In [1]:
from tensorflow import keras

In [2]:
# Load Data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(y_train.shape)

(60000,)


In [4]:
for i in range(5):
    print(y_train[i])

5
0
4
1
9


In [5]:
# one hot encoding 
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [6]:
for i in range(5):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [7]:
print(x_train.shape, x_test.shape)

(60000, 28, 28) (10000, 28, 28)


In [8]:
x_train = x_train.reshape([60000,28*28])
x_test = x_test.reshape([10000,28*28])

In [9]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [10]:
model = keras.Sequential()
model.add(keras.layers.Dense(32, activation="sigmoid", input_shape=(28*28,)))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(10, activation="sigmoid"))

In [11]:
optimizer = keras.optimizers.SGD(lr=0.1)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=['accuracy'])

model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 32)                25120     
_________________________________________________________________
dense_1 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_2 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_3 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_4 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_5 (Dense)              (None, 10)                330       
Total params: 29,674
Trainable params: 29,674
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(x_train, y_train,
          batch_size=32,
          epochs=10,
          validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================] - 27s 450us/step - loss: 2.3023 - acc: 0.1118 - val_loss: 2.3006 - val_acc: 0.1135
Epoch 2/10
60000/60000 [==============================] - 20s 333us/step - loss: 2.3010 - acc: 0.1122 - val_loss: 2.2996 - val_acc: 0.1135
Epoch 3/10
60000/60000 [==============================] - 21s 347us/step - loss: 2.2981 - acc: 0.1131 - val_loss: 2.2913 - val_acc: 0.1135
Epoch 4/10
60000/60000 [==============================] - 21s 347us/step - loss: 2.0666 - acc: 0.2045 - val_loss: 1.9842 - val_acc: 0.2350
Epoch 5/10
60000/60000 [==============================] - 21s 347us/step - loss: 1.8448 - acc: 0.2738 - val_loss: 1.8122 - val_acc: 0.2717
Epoch 6/10
60000/60000 [==============================] - 21s 346us/step - loss: 1.7549 - acc: 0.3210 - val_loss: 1.9016 - val_acc: 0.2514
Epoch 7/10
60000/60000 [==============================] - 21s 346us/step - loss: 1.7657 - acc: 0.3136 - val_loss: 1.

In [ ]:
model.evaluate(x_test,y_test)

In [ ]:
model.fit(x_train, y_train,
          batch_size=256,
          epochs=10,
          validation_data=(x_test, y_test))

model.evaluate(x_test,y_test)