In [1]:
from tensorflow import keras

In [2]:
# Load Data
(x_train, y_train), (x_test, y_test) = keras.datasets.mnist.load_data()

In [3]:
print(y_train.shape)

(60000,)


In [4]:
for i in range(5):
    print(y_train[i])

5
0
4
1
9


In [5]:
# one hot encoding 
y_train = keras.utils.to_categorical(y_train, 10)
y_test = keras.utils.to_categorical(y_test, 10)

In [6]:
for i in range(5):
    print(y_train[i])

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]


In [7]:
print(x_train.shape, x_test.shape)

(60000, 28, 28) (10000, 28, 28)


In [8]:
x_train = x_train.reshape([60000,28*28])
x_test = x_test.reshape([10000,28*28])

In [9]:
print(x_train.shape, x_test.shape)

(60000, 784) (10000, 784)


In [10]:
model = keras.Sequential()
model.add(keras.layers.Dense(32, activation="sigmoid", input_shape=(28*28,)))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(32, activation="sigmoid"))
model.add(keras.layers.Dense(10, activation="sigmoid"))

In [11]:
optimizer = keras.optimizers.SGD(lr=0.1)
model.compile(optimizer=optimizer, loss="categorical_crossentropy", metrics=['accuracy'])

model.summary()

Instructions for updating:
keep_dims is deprecated, use keepdims instead
Instructions for updating:
keep_dims is deprecated, use keepdims instead
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 32)                25120     
_________________________________________________________________
dense_2 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_3 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_4 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_5 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_6 (Dense)              (None, 32)                1056   

In [12]:
model.fit(x_train, y_train,
          batch_size=32,
          epochs=10,
          validation_data=(x_test, y_test))

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================]60000/60000 [==============================] - 4s 67us/step - loss: 2.3029 - acc: 0.1101 - val_loss: 2.3011 - val_acc: 0.1135

Epoch 2/10
60000/60000 [==============================]60000/60000 [==============================] - 4s 62us/step - loss: 2.3018 - acc: 0.1117 - val_loss: 2.3020 - val_acc: 0.1032

Epoch 3/10
60000/60000 [==============================]60000/60000 [==============================] - 4s 62us/step - loss: 2.3019 - acc: 0.1111 - val_loss: 2.3014 - val_acc: 0.1135

Epoch 4/10
60000/60000 [==============================]60000/60000 [==============================] - 4s 63us/step - loss: 2.3016 - acc: 0.1121 - val_loss: 2.3012 - val_acc: 0.1135

Epoch 5/10
60000/60000 [==============================]60000/60000 [==============================] - 4s 62us/step - loss: 2.3017 - acc: 0.1124 - val_loss: 2.3011 - val_acc: 0.1135

Epoch 6/10
60000/60000 [================

In [13]:
model.evaluate(x_test,y_test)

10000/10000 [==============================]10000/10000 [==============================] - 0s 27us/step



[2.301065668487549, 0.1135]

In [14]:
model.fit(x_train, y_train,
          batch_size=256,
          epochs=10,
          validation_data=(x_test, y_test))

model.evaluate(x_test,y_test)

Train on 60000 samples, validate on 10000 samples
Epoch 1/10
60000/60000 [==============================]60000/60000 [==============================] - 1s 15us/step - loss: 2.3013 - acc: 0.1124 - val_loss: 2.3010 - val_acc: 0.1135

Epoch 2/10
60000/60000 [==============================]60000/60000 [==============================] - 1s 15us/step - loss: 2.3012 - acc: 0.1124 - val_loss: 2.3010 - val_acc: 0.1135

Epoch 3/10
60000/60000 [==============================]60000/60000 [==============================] - 1s 15us/step - loss: 2.3012 - acc: 0.1124 - val_loss: 2.3010 - val_acc: 0.1135

Epoch 4/10
60000/60000 [==============================]60000/60000 [==============================] - 1s 15us/step - loss: 2.3012 - acc: 0.1124 - val_loss: 2.3010 - val_acc: 0.1135

Epoch 5/10
60000/60000 [==============================]60000/60000 [==============================] - 1s 15us/step - loss: 2.3012 - acc: 0.1124 - val_loss: 2.3010 - val_acc: 0.1135

Epoch 6/10
60000/60000 [================

[2.3010223609924316, 0.1135]